backend:
  image: backend:latest
  environment:
    - API_KEY=2594914d2f734dacaf3087503148c5d1
  ports:
    - 8080:8080

frontend:
  image: frontend:latest
  ports:
    - 3000:3000

seleniumhub:
  image: selenium/hub
  ports:
    - 4444:4444

firefoxnode:
  image: selenium/node-firefox-debug
  ports:
    - 4577
  links:
    - seleniumhub:hub

chromenode:
  image: selenium/node-chrome-debug
  ports:
    - 4578
  links:
    - seleniumhub:hub